### ISSUE TITLE
demo breaks, result undefined

### ISSUE THREAD

**Issue by redchair123** [dannymidnight/node-weather#2]
```
> var weather = require('weather');
> weather({lat: -50.212, long: 10.829}, function(data) { console.log(data); });
```

This is the demo in the README

I get an error:

```
TypeError: Cannot read property 'Found' of undefined
    at Request.yahoo.where [as _callback] (weather/yahoo.js:71:13)
    at Request.init.self.callback (weather/node_modules/request/main.js:119:22)
    at Request.<anonymous> (weather/node_modules/request/main.js:525:16)
    at Request.EventEmitter.emit (events.js:96:17)
    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (weather/node_modules/request/main.js:484:14)
    at IncomingMessage.EventEmitter.emit (events.js:126:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete] (http.js:149:23)
    at Socket.socketOnData [as ondata] (http.js:1367:20)
    at TCP.onread (net.js:404:27)
```

**Comment by dannymidnight** [comment]
@Niggler Looks like Yahoo has changed their weather API :grin: 

Apologies, I'll have a look at updating.
